### ISSUE TITLE
Consider moving the repo to `tree-sitter-grammars`

### ISSUE THREAD

**Issue by amaanq** [tree-sitter-grammars/tree-sitter-hcl#44]
Hey @MichaHoffmann, I hope you've been well. We at nvim-treesitter (and potentially more folks from other teams interested in an ecosystem-wide effort to maintain grammars) have decided to move all of our own grammars collectively into one org, to make it easier for us all to fix bugs or keep things up to date (scanner crashes, regenerating with the latest abi, etc.) without having to rely on one sole maintainer (you).

This is 100% optional, and please don't feel pressured or feel like you have an obligation of moving the grammar to the org, but it will help everyone a lot, us at nvim-treesitter, other users downstream, to know that a grammar won't ever die should a maintainer call it quits or go MIA. We also have org-wide actions that we maintain (out of sight, out of mind for you) and a grammar template (soon for newbies) in place to ensure authors have a better experience with working on and fixing tree-sitter grammars. It also enables anyone looking to find grammars for a specific language to only have to search in one spot

Our org is here: https://github.com/tree-sitter-grammars

If you want to participate (and don't worry, you'll still have full write perms to your repo, just no admin access), that'd be great! All you have to do is transfer the repo to me in the repository settings and I'll handle it from there. Thanks a lot, and again no worries if the answer is no!

**Comment by MichaHoffmann** [comment]
Yeah, lets do that!

**Comment by amaanq** [comment]
Nice! All you have to do is just transfer the repo to me from the settings page and then I'll move it to the org

**Comment by MichaHoffmann** [comment]
Ok, transfer is in progress

**Comment by amaanq** [comment]
Thank you so much! It's now at https://github.com/tree-sitter-grammars/tree-sitter-hcl and you should still have write access, let me know if not :)

**Comment by MichaHoffmann** [comment]
It was a fun project haha! Is there something we have to do to make it compliant with the rules of the organization? Github Actions, repo structure etc; let me know if i can help with something

**Comment by amaanq** [comment]
We're still in the process of structuring everything and getting more grammars in, but we do now have org-wide workflows and issue templates and so once that's solidified we'll begin having every repo use them instead 😁 for now there isn't much, I just checked and you never published the grammar(s) to crates or npm, so we can actually take care of that for you instead of requiring some form of access/rights to that

**Comment by MichaHoffmann** [comment]
Nah, i originally only wrote it for my own neovim+terraform usecase; so never had use for npm or rust

**Comment by amaanq** [comment]
makes sense; we want stability and keeping up to date across all platforms/registers ;)
